branches:
  only:
  - dev
  - master
language: node_js
node_js:
- '7'
- '8'
os:
- linux
# - osx
cache:
  yarn: true
  directories:
  - node_modules
install:
  - yarn
script:
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: URMMueZqWg3NGIDDkOYjhExYVHV5P0sWL1twtJEDHjPgl1ZJq5l9S2KNTI98/bzJVMTuXd1TaMki7Li5JEWjOhijE6rZSShHhcJ80Mn/l/oSoBmSyN6kT6FObpEtkwiaqLO8iqUbrbJY/r5qhhnAKeNcxoMfPmVkJMgndzqstQX/7qmLpELd3mpDrepxt/c8ElMtsZPotPx3+QJ0IH3bbU6eT1wZV3XyOMNHSp1edB9BZVW9qplP6+h77kPFeZPyy5RlPDzQS8V38Q8VunT9QGACHcfqnPt52pEpMZUJZNCW9iC+EFjcMeIZvgBIJEKLZNreDHqAjZeeWP4b7iemB3KdiqQFfT3hGTYaG4ocnK59oP7P+T6O/KhmFCdu1oLI8rohFBDVYSNjd6iuUCw/nsMDNHOCdHwO5UELglHV5wDeuORtbhmVPYh+7BUpzXvRv0A6+YZVtyAjPjnEOCmbpjy8zGLXpw+0YHo8nApi11ggbFTMXeCswBxGBltU/zgOyqCAn1nG5MQlYHnIJRzqjpvyBJ0mP8YhFktnsAgsgK6Gd1eSN3gWy2tMZAtTrGY+M7p9e8JI9ickJX/3beqRvy+ZuXGQx+ETuSGC+cpeYNP/klV22bh4CIfkG2zMyCEk1Df2eotmPriAQ/uyiS8RoN/KQC5zE+ai60ykBgSFYuQ=
  app: nuxt-hare
  on:
    branch: dev
    node: 8
    condition: "$TRAVIS_OS_NAME == linux"
